services:
  mysql-vehicle-db:
    image: mysql:8.0
    container_name: mysql-vehicle-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vehicle_api_db
    volumes:
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vehicle-network

networks:
  vehicle-network:
    driver: bridge
